### PR TITLE
appends posted attribute

### PR DESCRIPTION
**Pull request by koslo**
Is needed for pure API-use, all not appended attributes are missing...

### CODE REVIEW

**Comment by Riari** [comment]
Thanks for pointing that out. I think all of the models probably need their `$appends` properties to be updated, so I'm going to close this and deal with them all in one go.

Feel free to do a new PR if you want to go over them all.

**Comment by koslo** [comment]
I think adding all attributes is too much for an API. Most data can be generated in fronted. Some attributes crashes the app (nesting level over 512..., jsonSerialize errors).
Maybe its better to specify the models in the config so everyone feel free to extend it or a configurable set of appending data?
Working and useful attributes:
Post:
`['is_first', 'posted', 'updated']`
Thread:
`['last_post_time', 'reply_count', 'old', 'reader', 'user_read_status', 'posted', 'updated', 'slug']`
reply_count only working when quering the count
Category:
`['thread_count', 'post_count', 'depth', 'slug']`

**Comment by Riari** [comment]
Actually, backtracking a bit - I did include the ability to do Eloquent things RESTfully. http://teamteatime.net/docs/laravel-forum/3.x/api/request-scopes.md Does `?append[]=attribute` not work?

**Comment by koslo** [comment]
Sure, withRequestScopes is working fine.
But e.g. on saving/updating a post i put the returning data in the view model and here the attributes are missing. On the other side i am using own controller to return collected data for saving up requests.

**Pull request closed without merging**
